export const ACTIONS = {
  SUBMIT_LOGIN: 'SUBMIT_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  RESET_LOGIN: 'RESET_LOGIN'
};

export const APP ={
  BASE_PATH : "/ghack/login"
}
